export const GET_TIMES = 'GET_TIMES';
export const SET_SELECTION_DATE = 'SET_SELECTION_DATE';
export const SET_SELECTION_TIME = 'SET_SELECTION_TIME';
export const SET_SURNAME = 'SET_SURNAME';
export const SET_NAME = 'SET_NAME';

export const GET_BOOKINGS = 'GET_BOOKINGS';
export const CREATE_BOOKING = 'CREATE_BOOKING';